sensor:

  - platform: homeassistant
    entity_id: sensor.liam_bedroom_temperature
    id: office_temperature
    on_value:
      - lvgl.label.update:
          id: liam_bedroom_temperature
          text:
            format: "%d° / %d°"
            args: [ '(int)round(id(liam_bedroom_temperature).state)', '(int)round(x)' ]

switch:

  # Movie Light
  - platform: homeassistant
    id: living_room_sofa_light
    entity_id: switch.living_room_sofa_light
    on_state:
      then:
        lvgl.widget.update:
          id: living_room_sofa_light_button
          state:
            checked: !lambda return x;
